export const event =
{
  title: 'Самый известный монастырь',
  address: 'Самарская область, деревня Монастырево',
  programmTiming: 'Программа: 08:00 – отправление от департамента туризма министерства культуры Самарской области (г. Самара, Волжский проспект, 19) 11:00 – посещение «Маринино Подворье» с. Кузькино 13:00 – обед в кафе «Радуга» 14:30 – посещение гончара Александра Зайцева 15:45 – посещение турбазы Орбита 17:00 – Караульный бугор (гора Светёлка), п. Волжский Утес 18:00 – Шаманская поляна п. Волжский Утес 22:00 – прибытие к департаменту туризма министерства культуры Самарской области (г. Самара, Волжский проспект, 19)',
  shortDescription: 'Загородный комплекс «Орбита», гончарное мастерство и знакомство с крестьянским бытом в «Маринином Подворье»',
  dateEvent: '29.08.2021',
  participants: [
    {
      account: 'a.a.maximova',
      social: 'Instagram',
      firstName: 'Анна',
      lastName: 'Максимова',
      followers: '37465',
      following: '129',
      posts: '765',
      title: 'Пожила в 2х столицах, Путешествую по Самарской области, Пою, играю и изучаю психологию, Фотографирую',
      phone: '8-936-588-47-58',
      email: 'maximova@rambler.ru',
      location: 'Самара',
      countTravel: '2',
      comment: 'Основная часть подписчиков - жители Самары.',
      VisitedEvents: ['']
    },
    {
      account: '',
      social: 'СМИ',
      firstName: 'Олег',
      lastName: 'Тимофеев',
      followers: '',
      following: '',
      posts: '',
      title: '',
      phone: '8-433-996-44-55',
      email: 'timofeev@mail.ru',
      location: 'Москва',
      countTravel: '1',
      comment: 'Автор статей в газете "Комсомольская правда". Тираж 500 тыс. экземпляров',
      VisitedEvents: ['']
    },
    {
      account: 'Счастливы в путешествиях',
      social: 'youtube',
      firstName: 'Александр',
      lastName: 'Жестев',
      followers: '11860',
      following: '',
      posts: '187',
      title: 'Представляем Вашему вниманию наш канал "Счастливы в Путешествиях". Канал о наших путешествиях и не только. Будем рады каждому гостю посетившим нас!!!',
      phone: '8-453-767-55-97',
      email: 'zhesvev@mail.ru',
      location: 'Томск',
      countTravel: '2',
      comment: 'Путешествует в России. ',
      VisitedEvents: ['']
    },
    {
      account: 'ksuni_mi',
      social: 'Instagram',
      firstName: 'Ксения',
      lastName: 'Шибанова',
      followers: '9206',
      following: '265',
      posts: '1419',
      title: 'Творчество психолога, Сотрудничество @ksuni_mi_pr, Mom @mellani_mi, Веду @blogozhizn63',
      phone: '8-567-666-54-87',
      email: 'shibanonaks@mail.ru',
      location: 'Саратов',
      countTravel: '1',
      comment: 'Нет четкой направленности в постах',
      VisitedEvents: ['']
    },
  ]
}