const dataBase = [
  {
    account: "a.a.maximova",
    social: "Instagram",
    firstName: "Анна",
    lastName: "Максимова",
    followers: "37465",
    following: "129",
    posts: "765",
    title:
      "Пожила в 2х столицах, Путешествую по Самарской области, Пою, играю и изучаю психологию, Фотографирую",
    phone: "8-936-588-47-58",
    email: "maximova@rambler.ru",
    location: "Самара",
    countTravel: "2",
    comment: "Основная часть подписчиков - жители Самары.",
  },
  {
    account: "tastylife_yana",
    social: "Instagram",
    firstName: "Яна",
    lastName: "Смирнова",
    followers: "14500",
    following: "1860",
    posts: "234",
    title:
      "Моя вкусная жизнь, Снимаю аппетитные сторис, Делюсь рецептами и вдохновляю, Фудсъёмка для брендоя, Дважды мама",
    phone: "8-654-978-34-44",
    email: "smirnova@mail.ru",
    location: "Самара",
    countTravel: "1",
    comment:
      "Подписана на большое количество людей - скорей всего занимается накруткой подписчиков. Основная часть постов про питание / рецепты",
  },
  {
    account: "anastasia___cat_",
    social: "Instagram",
    firstName: "Анастасия",
    lastName: "Веселова",
    followers: "10276",
    following: "929",
    posts: "1180",
    title:
      "Model @lkmodels.63, Ambassador @game_samara, Блогер @anastasia___cat_",
    phone: "8-765-888-34-00",
    email: "veselova@mail.ru",
    location: "Самара",
    countTravel: "3",
    comment: "Фотомодель",
  },
  {
    account: "ksuni_mi",
    social: "Instagram",
    firstName: "Ксения",
    lastName: "Шибанова",
    followers: "9206",
    following: "265",
    posts: "1419",
    title:
      "Творчество психолога, Сотрудничество @ksuni_mi_pr, Mom @mellani_mi, Веду @blogozhizn63",
    phone: "8-567-666-54-87",
    email: "shibanonaks@mail.ru",
    location: "Саратов",
    countTravel: "1",
    comment: "Нет четкой направленности в постах",
  },
  {
    account: "",
    social: "СМИ",
    firstName: "Екатерина",
    lastName: "Афанасова",
    followers: "",
    following: "",
    posts: "",
    title: "",
    phone: "8-567-543-88-99",
    email: "afanasovaekat@mail.ru",
    location: "Самара",
    countTravel: "2",
    comment:
      'Журналист в газете "Новости Самары". Газета распространяется бесплатно. Тираж 80 тыс. экземпляров',
  },
  {
    account: "",
    social: "СМИ",
    firstName: "Олег",
    lastName: "Тимофеев",
    followers: "",
    following: "",
    posts: "",
    title: "",
    phone: "8-433-996-44-55",
    email: "timofeev@mail.ru",
    location: "Москва",
    countTravel: "1",
    comment:
      'Автор статей в газете "Комсомольская правда". Тираж 500 тыс. экземпляров',
  },
  {
    account: "Kung Fu Trip",
    social: "youtube",
    firstName: "Михаил",
    lastName: "Кирсанов",
    followers: "28100",
    following: "",
    posts: "65",
    title:
      "Путешествую выгодно и обучаю этому других в школе Kung Fu Trip, DJ / Travel & Lifestyle Blogger",
    phone: "8-654-543-09-65",
    email: "kirsanovmih@rambler.ru",
    location: "Москва",
    countTravel: "3",
    comment: "Видео хорошо смонтированы",
  },
  {
    account: "Happy Trips",
    social: "youtube",
    firstName: "Дмитрий",
    lastName: "Судаков",
    followers: "2880",
    following: "",
    posts: "35",
    title:
      "Всем привет! Мы любим путешествовать, снимать на видео наши поездки и делиться впечатлениями!",
    phone: "8-654-345-44-76",
    email: "sudacov@yandex.ru",
    location: "Волгоград",
    countTravel: "1",
    comment: "Путешествует в России и за границей",
  },
  {
    account: "Счастливы в путешествиях",
    social: "youtube",
    firstName: "Александр",
    lastName: "Жестев",
    followers: "11860",
    following: "",
    posts: "187",
    title:
      'Представляем Вашему вниманию наш канал "Счастливы в Путешествиях". Канал о наших путешествиях и не только. Будем рады каждому гостю посетившим нас!!!',
    phone: "8-453-767-55-97",
    email: "zhesvev@mail.ru",
    location: "Томск",
    countTravel: "2",
    comment: "Путешествует в России. ",
  },
];

export default dataBase;
