const items = [
  {
    id: 1,
    article: 245682,
    name: "Халат защитный Buba",
    quantity: 32,
    size: "S",
    discount: 10,
    cost: 1430,
    actionCost: 0,
  },
  {
    id: 2,
    article: 223122,
    name: "Костюм защитный Duda",
    quantity: 10,
    size: "L",
    discount: 0,
    cost: 1430,
    actionCost: 0,
  },
  {
    id: 3,
    article: 189143,
    name: "Костюм защитный Elizabet",
    quantity: 44,
    size: "L",
    discount: 0,
    cost: 1900,
    actionCost: 0,
  },
  {
    id: 4,
    article: 112199,
    name: "Костюм защитный Avganez",
    quantity: 23,
    size: "M",
    discount: 0,
    cost: 1900,
    actionCost: 0,
  },
  {
    id: 5,
    article: 155549,
    name: "Халат защитный",
    quantity: 44,
    size: "L",
    discount: 0,
    cost: 2500,
    actionCost: 0,
  },
];

export default items;
